### ISSUE TITLE
Multiple values for _expand ? 

### ISSUE THREAD

**Issue by ygagnon** [sparkapi/sparkapi4p2#54]
I've been using "**'_expand' => 'Photos'**" with the GetListing() method, and everything has been working fine.  However, I'm now trying to also retrieve Listing Documents (in addition to the Photos), and and am attempting to do so using "**'_expand' => 'Photos, Documents'**", but Documents it's returning an empty array.  Can I specify multiple values when assigning the "_expand" parameter?  If so, then what is the correct syntax for retrieving both Photos and Documents?

Thanks,
-- Yvan

**Comment by dgmyrek** [comment]
You are making the request in the correct manner and since the response contains the "Documents" attribute that confirms that your request is successful. In this instance the listings do not have any publicly accessible documents attached. This either signifies that the listing agent has not uploaded any documents or all documents in the MLS associated with that listing have been marked "private".

**Comment by ygagnon** [comment]
Ah .. I see.  You are correct.  Thank you.
